# Generated by Django 5.2.1 on 2025-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
